name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Pull the code from your GitHub repo into the runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Log in to your Docker Hub account
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Set up Docker Buildx (for advanced caching/multi-platform)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build and Push the image
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .               # The root of your project
          file: ./producer/Dockerfile # The path to your Dockerfile
          push: true               # Upload it to the cloud
          # Tags the image with 'latest' and the specific Git commit hash
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-test:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-test:${{ github.sha }}